# Generated by Django 2.2 on 2019-10-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabelas', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.CharField(max_length=20, verbose_name='Número de Registro')),
                ('fabricante', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('escala_ini', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Escala Inicial')),
                ('escala_fim', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Escala Final')),
                ('num_serie', models.CharField(max_length=20, verbose_name='Número de Série')),
                ('tag', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Pendente')], default=1, max_length=10, verbose_name='Status')),
                ('n_estrategia', models.IntegerField()),
                ('departamento', models.CharField(max_length=20, verbose_name='Departamento')),
                ('resolucao_1', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Resolução 1')),
                ('resolucao_2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Resolução 2')),
                ('dt_criacao', models.DateTimeField(auto_now=True)),
                ('desvio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabelas.Desvio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.Tipo_equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabelas.Usuario')),
            ],
        ),
    ]
