# Generated by Django 2.2 on 2019-12-08 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabelas', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Registro')),
                ('fabricante', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('escala', models.CharField(blank=True, max_length=30, null=True)),
                ('num_serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Série')),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('n_estrategia', models.IntegerField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Departamento')),
                ('resolucao_1', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Resolução 1')),
                ('resolucao_2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Resolução 2')),
                ('dt_criacao', models.DateTimeField(auto_now=True)),
                ('pontos_calib', models.CharField(blank=True, max_length=50, null=True)),
                ('desvio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Desvio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.Tipo_equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
