# Generated by Django 3.0 on 2020-01-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='status',
            new_name='ativo',
        ),
    ]
