# Generated by Django 2.2 on 2019-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='escala_fim',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='escala_ini',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='escala',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
