# Generated by Django 2.2 on 2019-10-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_auto_20191021_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='departamento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='desvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Desvio'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='n_estrategia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='num_registro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Registro'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='num_serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.Tipo_equipamento'),
        ),
    ]
