# Generated by Django 2.2 on 2019-12-08 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabelas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa_nominal_g', models.FloatField()),
                ('marcacao', models.CharField(max_length=20)),
                ('classe', models.CharField(blank=True, choices=[('E1', 'E1'), ('E2', 'E2'), ('F1', 'F1'), ('F2', 'F2'), ('M1', 'M1'), ('M2', 'M2')], max_length=20, null=True)),
                ('identificacao', models.CharField(max_length=20)),
                ('massa_conv_mg_1', models.FloatField()),
                ('erro_1', models.FloatField()),
                ('massa_conv_mg_2', models.FloatField()),
                ('erro_2', models.FloatField()),
                ('dt_calibracao', models.DateField()),
                ('validade', models.DateField()),
                ('material', models.CharField(choices=[('Aço Inoxidável', 'ACO_INOXIDAVEL'), ('Ferro Fundido', 'FERRO_FUNDIDO')], max_length=20)),
                ('incerteza_mg', models.FloatField()),
                ('certificado', models.CharField(max_length=20)),
                ('fator_abrangencia', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('dt_criacao', models.DateTimeField(auto_now=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabelas.Conjunto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabelas.Unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calibracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidade', models.IntegerField()),
                ('dt_calib', models.DateField(auto_now=True, verbose_name='Data Calibração')),
                ('dt_calib_next', models.DateField(verbose_name='Próxima Calibração')),
                ('ajuste', models.CharField(blank=True, max_length=30, null=True)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pressao', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('desvio_adotado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Desvio Adotado')),
                ('tipo_calibracao', models.CharField(blank=True, max_length=10, null=True)),
                ('num_os', models.IntegerField(blank=True, null=True, verbose_name='Número OS')),
                ('dt_criacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calibracoes.Certificado')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.Equipamento')),
                ('pesos', models.ManyToManyField(to='calibracoes.Peso')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Calibracao_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calibracoes',
            },
        ),
    ]
