# Generated by Django 3.0 on 2020-01-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peso',
            old_name='status',
            new_name='ativo',
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'PROCESSING'), ('finished', 'FINISHED'), ('Aborted', 'ABORTED')], max_length=20, null=True),
        ),
    ]
