# Generated by Django 2.2 on 2019-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracao',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
