# Generated by Django 2.2 on 2019-10-22 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0002_calibracao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Calibracao_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
