# Generated by Django 2.2 on 2019-10-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0003_auto_20191021_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='classe',
            field=models.CharField(blank=True, choices=[('E1', 'E1'), ('E2', 'E2'), ('F1', 'F1'), ('F2', 'F2'), ('M1', 'M1'), ('M2', 'M2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='peso',
            name='material',
            field=models.CharField(choices=[('Aço Inoxidável', 'ACO_INOXIDAVEL'), ('Ferro Fundido', 'FERRO_FUNDIDO')], max_length=20),
        ),
    ]
