# Generated by Django 2.2 on 2019-11-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0004_auto_20191030_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peso',
            name='conjunto',
        ),
        migrations.DeleteModel(
            name='Conjunto',
        ),
    ]
