# Generated by Django 2.2 on 2019-10-31 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibracoes', '0004_auto_20191030_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='conjunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabelas.Conjunto'),
        ),
        migrations.DeleteModel(
            name='Conjunto',
        ),
    ]
