# Generated by Django 2.2 on 2019-11-02 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0005_auto_20191030_2348'),
        ('calibracoes', '0005_auto_20191102_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso',
            name='conjunto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Conjunto'),
            preserve_default=False,
        ),
    ]
