# Generated by Django 2.2 on 2019-10-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio',
            field=models.CharField(max_length=50),
        ),
    ]
