# Generated by Django 2.2 on 2019-10-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20191016_2205'),
        ('tabelas', '0002_auto_20191016_2138'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
