# Generated by Django 2.2 on 2019-10-22 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_auto_20191021_2250'),
        ('calibracoes', '0003_auto_20191021_2250'),
        ('tabelas', '0003_auto_20191016_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
