# Generated by Django 2.2 on 2019-10-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Grupo_Empresas',
        ),
    ]
