# Generated by Django 2.2 on 2019-12-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ')),
                ('ie', models.CharField(blank=True, max_length=14, null=True, verbose_name='Inscrição Estadual')),
                ('nome_razao', models.CharField(max_length=100, verbose_name='Nome/Razão')),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Fantasia')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('dt_criacao', models.DateTimeField(auto_now=True)),
                ('tipo_log', models.CharField(blank=True, choices=[('Rua', 'Rua'), ('Av', 'Av'), ('Rod', 'Rod'), ('Outro', 'Outro')], default='1', max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(blank=True, max_length=30, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_tel', models.CharField(blank=True, choices=[('Fone', 'Fone'), ('Cel', 'Cel'), ('Outro', 'Outro')], default='1', max_length=10, null=True)),
                ('ddd', models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD')),
                ('num_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('unidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
