# Generated by Django 2.2 on 2019-10-15 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='num_tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('1', 'Fone'), ('2', 'Cel'), ('3', 'Outro')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_log',
            field=models.CharField(choices=[('1', 'Rua'), ('2', 'Av'), ('3', 'Rod'), ('4', 'Outro')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Estado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
