# Generated by Django 2.2 on 2019-10-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20191014_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ie',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Municipio'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Pais'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1', 'Fone'), ('2', 'Cel'), ('3', 'Outro')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_log',
            field=models.CharField(blank=True, choices=[('1', 'Rua'), ('2', 'Av'), ('3', 'Rod'), ('4', 'Outro')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.Estado'),
        ),
    ]
