# Generated by Django 2.2 on 2019-10-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20191014_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
