# Generated by Django 2.2 on 2019-10-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20191020_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='unidade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
