# Generated by Django 2.2 on 2019-10-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_auto_20191020_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ie',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
