# Generated by Django 2.2 on 2019-10-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_auto_20191020_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo_log',
            field=models.CharField(blank=True, choices=[('Rua', 'Rua'), ('Av', 'Av'), ('Rod', 'Rod'), ('Outro', 'Outro')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_tel',
            field=models.CharField(blank=True, choices=[('Fone', 'Fone'), ('Cel', 'Cel'), ('Outro', 'Outro')], default='1', max_length=10, null=True),
        ),
    ]
